# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='source_ip',
        ),
    ]
